version: '3.6'
services:
  wildfly:
    build:
      context: ../../builds/wildfly-dist
    container_name: wildfly-goib
    environment:
     - ADMIN_USER=admin
     - ADMIN_PASSWORD=admin
    ports:
     - 8080:8080
     - 9990:9990
    volumes:
     - /tmp/deployments:/opt/jboss/wildfly/standalone/deployments
     # - C:\tmp\deployments:/opt/jboss/wildfly/standalone/deployments
    depends_on:
      - keycloak
  keycloak:
    build:
      context: ../../builds/keycloak-dist
    container_name: keycloak-goib
    environment:
     - KEYCLOAK_USER=admin
     - KEYCLOAK_PASSWORD=admin
     - KEYCLOAK_IMPORT=/tmp/import-goib-realm.json
    ports:
     - 8180:8180
    volumes: 
      - ../../builds/keycloak-dist/keycloak/conf/import-goib-realm.json:/tmp/import-goib-realm.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak-goib:8180/auth/realms/GOIB"]
      interval: 10s
      timeout: 10s
      retries: 5
  appserver:
    image: tomcat:alpine
    container_name: scsp-tomcat
    hostname: scsptomcat
    restart: always
    ports:
      - "18080:8080"
      - "18443:8443"
    volumes: 
      - ../../builds/tomcat-dist/tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ../../builds/tomcat-dist/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
      - ../../builds/tomcat-dist/tomcat/conf/Catalina/localhost/context.xml:/usr/local/tomcat/conf/Catalina/localhost/manager.xml:ro
      - ../../builds/tomcat-dist/tomcat/conf/Catalina/localhost/context.xml:/usr/local/tomcat/conf/Catalina/localhost/host-manager.xml:ro
      - ../../builds/tomcat-dist/tomcat/certificados/ssl:/usr/local/tomcat/certificados/ssl:ro
      - ../../builds/tomcat-dist/tomcat/certificados/afirma:/usr/local/tomcat/certificados/afirma:ro
      - ../../builds/tomcat-dist/tomcat/logs:/usr/local/tomcat/logs
      - ../../builds/tomcat-dist/tomcat/lib/postgresql-42.2.16.jar:/usr/local/tomcat/lib/postgresql-42.2.16.jar:ro
      - ../../builds/tomcat-dist/tomcat/webapps/TestConfiguracion/TestConfiguracion.war:/usr/local/tomcat/webapps/TestConfiguracion.war:ro
      - ../../builds/tomcat-dist/tomcat/webapps/scsp-admin/scsp-admin.war:/usr/local/tomcat/webapps/scsp-admin.war:ro
    depends_on: 
      - scsp-emisor-db
      - scsp-admin-db
  scsp-emisor-db:
    build:
      context: ../../builds/postgresql-dist
    container_name: scsp-emisor-pg
    hostname: scsp-emisor-pg
    restart: always
    ports:
      - "5441:5432"
    volumes:
      - ../../builds/postgresql-dist/postgresql/scsp_emisor/data:/var/lib/postgresql/data
      - ../../builds/postgresql-dist/postgresql/scsp_emisor/tablespaces:/var/lib/postgresql/app/tablespaces
    environment:
      - POSTGRES_PASSWORD=postgres
      - LONG_APP_NAME=scsp_emisor
      - SHORT_APP_NAME=emi
  scsp-admin-db:
    build:
      context: ../../builds/postgresql-dist
    container_name: scsp-admin-pg
    hostname: scsp-admin-pg
    restart: always
    ports:
      - "5442:5432"
    volumes:
      - ../../builds/postgresql-dist/postgresql/scsp_admin/data:/var/lib/postgresql/data
      - ../../builds/postgresql-dist/postgresql/scsp_admin/tablespaces:/var/lib/postgresql/app/tablespaces
    environment:
      - POSTGRES_PASSWORD=postgres
      - LONG_APP_NAME=scsp_admin
      - SHORT_APP_NAME=adm



    
